name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: devsecops-llm-pipeline

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
    
      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Check if S3 Bucket Exists
        id: check-bucket
        run: |
          if aws s3api head-bucket --bucket ${{ env.BUCKET_NAME }} 2>/dev/null; then
            echo "Bucket exists."
            echo "BUCKET_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Bucket does not exist."
            echo "BUCKET_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Import S3 Bucket to Terraform State
        if: env.BUCKET_EXISTS == 'false'
        run: terraform import aws_s3_bucket.devsecops-llm-pipeline ${{ env.BUCKET_NAME }}
        working-directory: ./terraform/
    
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform/

      - name: Terraform Apply
        if: success()
        run: terraform apply -auto-approve
        working-directory: ./terraform/
