name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
    
      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform/

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform/

      - name: Import S3 Bucket
        run: terraform import aws_s3_bucket.devsecops-llm-pipeline devsecops-llm-pipeline
        working-directory: ./terraform/

      - name: Terraform Apply
        if: success()
        run: terraform apply -auto-approve
        working-directory: ./terraform/
        env:
          TF_LOG: DEBUG
