# Trigger only when files in the terraform/ directory (IaC) are updated
name: Terraform Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AMI_ID: ${{ secrets.AMI_ID }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      INSTANCE_TYPE: ${{ secrets.INSTANCE_TYPE }}
      SG_NAME: ${{ secrets.SG_NAME }}
      KEY_NAME: ${{ secrets.KEY_NAME }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
    
      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11
  
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/

      - name: Check and Import S3 Bucket
        run: bash ../scripts/manage-bucket.sh ${{ env.BUCKET_NAME }}
        working-directory: ./terraform/

      - name: Run Terraform Plan and Apply
        run: |
          chmod +x ../scripts/terraform-run.sh
          ../scripts/terraform-run.sh apply
        working-directory: ./terraform/
